
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173

database:
  default:
    link: "mysql:root:cyw162370.@tcp(127.0.0.1:3306)/golearning?loc=Local&parseTime=true"

gfcli:
  gen:
    dao:
    - link:     "mysql:root:cyw162370.@tcp(127.0.0.1:3306)/golearning?loc=Local&parseTime=true"
      tables:   "products,admin"