// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package damo

import (
	"golearning-goframe/api/damo"
)

type ControllerV1 struct{}

func NewV1() damo.IDamoV1 {
	return &ControllerV1{}
}
